name: Run Kick fetcher
run: python kick/generate_raport_kick.py
on:
  schedule:
    - cron: '*/30 * * * *'   # Odpala co 30 minut
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Kick fetcher
        run: python path/do/kick_fetcher.py

      - name: Commit & push updated cache
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add path/do/kick_clips_cache.json
          git commit -m "Auto-update: kick clips cache" || echo "Nothing to commit"
          git push
