services:
  - type: web
    name: twitch-clips-app
    env: python
    region: eu-central-1      # lub twoja strefa
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --log-file -
    envVars:
      - key: dbyhzaj41rmi10ftewy1sg2oux0bbs
      - key: yqmxhf241lbv9yoymtfkjyhuz17yxf

cronJobs:
  - name: update-streamers
    schedule: "*/30 * * * *"    # co 30 minut
    command: python update_streamers.py
    envVars:
      - key: dbyhzaj41rmi10ftewy1sg2oux0bbs
      - key: yqmxhf241lbv9yoymtfkjyhuz17yxf

