name: Kick fetcher

on:
  schedule:
    - cron: '*/20 * * * *' # co 20 minut
  workflow_dispatch:

permissions:
  contents: write
  
jobs:

  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Kick fetcher
        run: python kick/scrape_kick_clips.py
      - name: Commit & push updated cache
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add kick/kick_clips_cache.json
          git commit -m "Auto-update: kick clips cache" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Kquxxi/TwitchApp.git HEAD:main

