name: Kick fetcher

on:
  schedule:
    - cron: '*/30 * * * *'   # co 30 minut
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # potrzebne do przełączania branchy
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Kick fetcher
        run: python kick/scrape_kick_clips.py

      # >>> najważniejsza zmiana: osobna gałąź + force-push <<<
      - name: Commit & push updated cache (force to kick-cache)
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          # przełącz na/utwórz gałąź kick-cache
          git fetch --all --prune
          git checkout -B kick-cache

          git add kick/kick_clips_cache.json
          git commit -m "update kick cache" || echo "No changes"

          # nadpisz historię tej gałęzi jednym commitem
          git push -f origin HEAD:kick-cache
